"""user and employee models

Revision ID: 454a08bdcde4
Revises: 
Create Date: 2026-04-30 10:36:04.683260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '454a08bdcde4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=10), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('Admin', 'Employee', name='userrole'), nullable=False),
    sa.Column('status', sa.Enum('Active', 'Inactive', name='accountstatus'), nullable=False),
    sa.Column('inactive_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
