"""added constraints

Revision ID: d587e34a977b
Revises: 7866b0cadd9e
Create Date: 2026-05-04 08:00:42.927145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd587e34a977b'
down_revision = '7866b0cadd9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_employee_date', ['employee_id', 'date'])

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['employee_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.drop_constraint('uq_employee_date', type_='unique')

    # ### end Alembic commands ###
